name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v23
      - run: nix develop --command just -- build
      - run: nix develop --command just -- _generate-ssh-keys
      - run: |
          export SSH_KEY=${PWD}/id_rsa
          nix develop --command just -- test
